# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
        environment:
          TZ: Asia/Tokyo
    working_directory: /tmp/luckblog
    steps:
      - checkout
      - run: npm install
      - run: npm install --save-dev firebase-tools
      - run: node_modules/.bin/hexo clean
      - run: node_modules/.bin/hexo generate
      - run:
          name: 'Deploy to Hosting'
          command: node_modules/.bin/firebase deploy --only hosting --project "$FIREBASE_PROJECT_ID" --token "$FIREBASE_TOKEN"
      - run:
          name: 'Trigger build of lucknetwork.jp'
          command: curl -u $CIRCLE_API_USER_TOKEN -d build_parameters[CIRCLE_JOB]=workflow https://circleci.com/api/v1.1/project/github/lucknet/web/tree/master
