# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# friends link
links:
  - name: Web
    url: https://lucknetwork.jp

menu:
  - name: ホーム
    slug: home
    url: /
  - name: アーカイブ
    slug: archives
    url: /archives

# widgets
widgets:
  - about
  - links
  - categories
  - tagcloud

# Less
less:
  compress: true

# use url, not username
social:
- slug: twitter
  url: https://twitter.com/McLuckServer
- slug: rss
	url: /atom.xml
